### ISSUE TITLE
Store retry attempt number

### ISSUE THREAD

**Issue by nikophil** [SymfonyCasts/messenger-monitor-bundle#23]

**Comment by nikophil** [comment]
don't know if this is relevant... WDYT @weaverryan  ?

**Comment by weaverryan** [comment]
I'd say no. This data is stored inside stamps on individual messages, so I think it isn't needed.

**Comment by nikophil** [comment]
It is not stored when the user does retry from our bundle

**Comment by weaverryan** [comment]
So, perfect :). Shall we close?

**Comment by nikophil** [comment]
hmmm i don't know
> This data is stored inside stamps on individual messages
this is not true when the user clicks on "retry" from our dashboard, or maybe we should add another `RedeliveryStamp` (maybe a special one which says it has been retried manually?)

**Comment by weaverryan** [comment]
Ah, you're referring to "retried from failure queue" - it's always confusing because we have normal retries and then that OTHER type of retry, from the failure queue :). 

Yea... for now, I think I'm ok without having this.
