### ISSUE TITLE
Add rejected at field

### ISSUE THREAD

**Issue by nikophil** [SymfonyCasts/messenger-monitor-bundle#26]

**Comment by nikophil** [comment]
i don't know as well if this is relevant... @weaverryan

**Comment by weaverryan** [comment]
My instinct is that it is *not* relevant. If something, for example, ends up in the failure queue, it already has a stamp with a lot of details on it. We would only need a rejectedAt (I think) if we wanted to display some sort of aggregate data about all rejected messages.

**Comment by nikophil** [comment]
ok, let's close this one :)
